### ISSUE TITLE
Rebel YT2400 Pilots not pulling in R2D7

### ISSUE THREAD

**Issue by BuddyHG** [sebald/pattern-analyzer#429]
YT2400 Pilots are not showing in Discord when posted from a YASB link. LBN links work.

Original issue was reported to YASB via:
https://github.com/raithos/xwing/issues/1394

Reported fixed via::
https://github.com/raithos/xwing/issues/1395

Reported issue was ongoing and then redirected to R2D7 then Pattern Analyzer via:
https://github.com/raithos/xwing/issues/1400

**Comment by sebald** [comment]
Updated the YASB data. fixed. thanks for reporting :)
